### ISSUE TITLE
Test inference of model on cpu and python3

### ISSUE THREAD

**Issue by MetaDev** [xingyizhou/pytorch-pose-hg-3d#17]
I would like to test the trained model in python 3 and on cpu.
Right now I'm having issues with loading the model.

Traceback (most recent call last):
  File "demo.py", line 31, in <module>
    main()
  File "demo.py", line 13, in main
    model = torch.load(opt.loadModel).cuda()
  File "/home/hdbondt/miniconda3/lib/python3.6/site-packages/torch/serialization.py", line 231, in load
    return _load(f, map_location, pickle_module)
  File "/home/hdbondt/miniconda3/lib/python3.6/site-packages/torch/serialization.py", line 379, in _load
    result = unpickler.load()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 875: ordinal not in range(128)

Is there by any chance a trained version compatible with python3?

**Comment by xingyizhou** [comment]
Sorry I don't have it.

**Comment by tom1994** [comment]
@MetaDev I have the "Stage1" model file which has been trained in Python3 [model_60.pth](https://drive.google.com/file/d/1Iyt76gA-pwjSZUNcZMHTTKE0zWVTDvxR/view?usp=sharing)

**Comment by xingyizhou** [comment]
Thanks @tom1994 !
