### ISSUE TITLE
Demo.py issue: 'ascii' codec can't decode byte 0xc3 in position 875

### ISSUE THREAD

**Issue by marv17** [xingyizhou/pytorch-pose-hg-3d#28]
Hey, trying to run the demo, I'm receiving the following error. Any suggestions on how to fix it? Thank you!

(base) D:\xx\Pose\src>python demo.py -demo images/h36m_1214.png
Traceback (most recent call last):
  File "demo.py", line 31, in <module>
    main()
  File "demo.py", line 15, in main
    model = torch.load('hgreg-3d.pth').cuda()
  File "C:\Users\xx\Anaconda3\lib\site-packages\torch\serialization.py", line 303, in load
    return _load(f, map_location, pickle_module)
  File "C:\Users\xx\Anaconda3\lib\site-packages\torch\serialization.py", line 469, in _load
    result = unpickler.load()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 875: ordinal not in range(128)

**Comment by DNALuo** [comment]
HI, @marv17 . I have the same problem. Would you mind saying how you solve the problem?

**Comment by DNALuo** [comment]
@marv17 It solves the problem. Thank you so much.
