### ISSUE TITLE
Questions about training

### ISSUE THREAD

**Issue by Ssrzbao** [xingyizhou/pytorch-pose-hg-3d#51]
I have no problem running the demo of the test.But when I run the "python main.py -expID Stage1",I have encountered the following problem：
**
THCudaCheck FAIL file=d:\pytorch\pytorch\torch\lib\thc\generic/THCTensorMathPointwise.cu line=606 error=30 : unknown error
Traceback (most recent call last):
  File "H:/SZS/pytorch-pose-hg-3d-v0.0/src/main.py", line 84, in <module>
    main()
  File "H:/SZS/pytorch-pose-hg-3d-v0.0/src/main.py", line 65, in main
    loss_train, acc_train, mpjpe_train, loss3d_train = train(epoch, opt, train_loader, model, criterion, optimizer)
  File "H:\SZS\pytorch-pose-hg-3d-v0.0\src\train.py", line 61, in train
    return step('train', epoch, opt, train_loader, model, criterion, optimizer)
  File "H:\SZS\pytorch-pose-hg-3d-v0.0\src\train.py", line 51, in step
    optimizer.step()
  File "D:\anaconda\envs\Pytorch3\lib\site-packages\torch\optim\rmsprop.py", line 75, in step
    square_avg.mul_(alpha).addcmul_(1 - alpha, grad, grad)
RuntimeError: cuda runtime error (30) : unknown error at d:\pytorch\pytorch\torch\lib\thc\generic/THCTensorMathPointwise.cu:606
**
I have no idea about it. Would you help me?

**Comment by xingyizhou** [comment]
I have no idea either. It seems that you haven't installed pytorch correctly. Can you run the official pytorch examples?
