### ISSUE TITLE
Error Benchmark Testing

### ISSUE THREAD

**Issue by NguyenDangBinh** [xingyizhou/pytorch-pose-hg-3d#56]
dear,
I met the error like that
![image](https://user-images.githubusercontent.com/30711163/51076707-ec03df80-16d6-11e9-88d6-5bbbc279643d.png)

**Comment by NguyenDangBinh** [comment]
> dear,
> I met the error like that
> ![image](https://user-images.githubusercontent.com/30711163/51076707-ec03df80-16d6-11e9-88d6-5bbbc279643d.png)

**Comment by xingyizhou** [comment]
Hi, 
  CPU training is not supported in this project.

**Comment by NguyenDangBinh** [comment]
Dear,
I had GPU and I had the error below
(tensorflow-gpu) D:\Binh\pytorch-pose-hg-3d-master\pytorch-pose-hg-3d-master>python src/main.py --exp_id test --task human3d --dataset fusion_3d --load_model models/fusion_3d_var.pth --test --full_test
USE_TENSORBOARD:  False
heads {'hm': 16, 'depth': 16}
'cp' 不是內部或外部命令、可執行的程式或批次檔。
=> using msra resnet 'msra_50'
=> loading pretrained model https://download.pytorch.org/models/resnet50-19c8e357.pth
loaded models/fusion_3d_var.pth, epoch 10
==> initializing 3D val data.
Loaded 3D val 19312 samples
#Images2D 0, #Images3D 19312
USE_TENSORBOARD:  False
Traceback (most recent call last):
  File "src/main.py", line 103, in <module>
    main(opt)
  File "src/main.py", line 59, in main
    log_dict_train, preds = val(0, opt, val_loader, model)
  File "D:\Binh\pytorch-pose-hg-3d-master\pytorch-pose-hg-3d-master\src\lib\train_3d.py", line 147, in val_3d
    return step('val', epoch, opt, val_loader, model)
  File "D:\Binh\pytorch-pose-hg-3d-master\pytorch-pose-hg-3d-master\src\lib\train_3d.py", line 38, in step
    for i, batch in enumerate(data_loader):
  File "C:\Users\user\Anaconda3\envs\tensorflow-gpu\lib\site-packages\torch\utils\data\dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "C:\Users\user\Anaconda3\envs\tensorflow-gpu\lib\site-packages\torch\utils\data\dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
AttributeError: Traceback (most recent call last):
  File "C:\Users\user\Anaconda3\envs\tensorflow-gpu\lib\site-packages\torch\utils\data\dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "C:\Users\user\Anaconda3\envs\tensorflow-gpu\lib\site-packages\torch\utils\data\dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "D:\Binh\pytorch-pose-hg-3d-master\pytorch-pose-hg-3d-master\src\lib\datasets\fusion_3d.py", line 34, in __getitem__
    return self.dataset3D[index]
  File "D:\Binh\pytorch-pose-hg-3d-master\pytorch-pose-hg-3d-master\src\lib\datasets\h36m.py", line 96, in __getitem__
    s = min(s, max(img.shape[0], img.shape[1])) * 1.0
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by xingyizhou** [comment]
Hi, it seems that you haven't set up the image path correctly. You can add `print('path')` after https://github.com/xingyizhou/pytorch-pose-hg-3d/blob/master/src/lib/datasets/h36m.py#L55 to see if the path exists on your computer.

**Comment by NguyenDangBinh** [comment]
dear,
I fix the image path but the same error.
![image](https://user-images.githubusercontent.com/30711163/51554303-f2047800-1eaf-11e9-8fe9-c5c8f17c63f6.png)


I download the folder like that
![image](https://user-images.githubusercontent.com/30711163/51554652-be761d80-1eb0-11e9-8db7-33b200af0aef.png)
