### ISSUE TITLE
How to test Benchmark

### ISSUE THREAD

**Issue by NguyenDangBinh** [xingyizhou/pytorch-pose-hg-3d#62]
dear,
I use GPU,
I have the error.
(tensorflow-gpu) D:\Binh\pytorch-pose-hg-3d-master\pytorch-pose-hg-3d-master>python src/main.py --exp_id test --task human3d --dataset fusion_3d --load_model models/fusion_3d_var.pth --test --full_test
USE_TENSORBOARD:  False
heads {'hm': 16, 'depth': 16}
'cp' 不是內部或外部命令、可執行的程式或批次檔。
=> using msra resnet 'msra_50'
=> loading pretrained model https://download.pytorch.org/models/resnet50-19c8e357.pth
loaded models/fusion_3d_var.pth, epoch 10
==> initializing 3D val data.
Loaded 3D val 19312 samples
#Images2D 0, #Images3D 19312
USE_TENSORBOARD:  False
Traceback (most recent call last):
  File "src/main.py", line 103, in <module>
    main(opt)
  File "src/main.py", line 59, in main
    log_dict_train, preds = val(0, opt, val_loader, model)
  File "D:\Binh\pytorch-pose-hg-3d-master\pytorch-pose-hg-3d-master\src\lib\train_3d.py", line 147, in val_3d
    return step('val', epoch, opt, val_loader, model)
  File "D:\Binh\pytorch-pose-hg-3d-master\pytorch-pose-hg-3d-master\src\lib\train_3d.py", line 38, in step
    for i, batch in enumerate(data_loader):
  File "C:\Users\user\Anaconda3\envs\tensorflow-gpu\lib\site-packages\torch\utils\data\dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "C:\Users\user\Anaconda3\envs\tensorflow-gpu\lib\site-packages\torch\utils\data\dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
AttributeError: Traceback (most recent call last):
  File "C:\Users\user\Anaconda3\envs\tensorflow-gpu\lib\site-packages\torch\utils\data\dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "C:\Users\user\Anaconda3\envs\tensorflow-gpu\lib\site-packages\torch\utils\data\dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "D:\Binh\pytorch-pose-hg-3d-master\pytorch-pose-hg-3d-master\src\lib\datasets\fusion_3d.py", line 34, in __getitem__
    return self.dataset3D[index]
  File "D:\Binh\pytorch-pose-hg-3d-master\pytorch-pose-hg-3d-master\src\lib\datasets\h36m.py", line 96, in __getitem__
    s = min(s, max(img.shape[0], img.shape[1])) * 1.0
AttributeError: 'NoneType' object has no attribute 'shape'
Can you help me?

**Comment by NguyenDangBinh** [comment]
dear,
What is it mean?
python main.py --exp_id test --task human3d --dataset fusion_3d --load_model ../models/fusion_3d_var.pth --test --full_test
