### ISSUE TITLE
demo  has error

### ISSUE THREAD

**Issue by henbucuoshanghai** [xingyizhou/pytorch-pose-hg-3d#98]
python demo.py --demo ../images/mpi_inf_3dhp_1456.png --load_model ../hgreg-3d.pth 
heads {'hm': 16}
=> using msra resnet 'msra_50'
Downloading: "https://download.pytorch.org/models/resnet50-19c8e357.pth" to /home/featurize/.cache/torch/hub/checkpoints/resnet50-19c8e357.pth
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████| 97.8M/97.8M [00:00<00:00, 111MB/s]
=> loading pretrained model https://download.pytorch.org/models/resnet50-19c8e357.pth
Traceback (most recent call last):
  File "demo.py", line 80, in <module>
    main(opt)
  File "demo.py", line 60, in main
    model, _, _ = create_model(opt)
  File "/home/featurize/work/Pytorch-pose-hg-3d/src/lib/model.py", line 20, in create_model
    opt.load_model, map_location=lambda storage, loc: storage)
  File "/environment/miniconda3/lib/python3.7/site-packages/torch/serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/environment/miniconda3/lib/python3.7/site-packages/torch/serialization.py", line 787, in _legacy_load
    result = unpickler.load()
ModuleNotFoundError: No module named 'models.hg_3d'

**Comment by henbucuoshanghai** [comment]
where is wrong?  the code i change nothing...
tks
